const data = [
    {
        displayName: "No Brainer Meals",
        name: "NoBrainerMeals",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075793/nobrainermeals_e1bpca.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075793/nobrainermeals_e1bpca.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "Material Design",
            "C#",
            ".NET",
            "MSSQL"
        ],
        features: [
            "Admin users can create recipes",
            "Admin users can upload photos",
            "Admin users can link suggested equipment",
            "Users can create accounts",
            "Recipes can have multiple ingredients sources with links, amounts, and prices",
            "Users can view price per serving for each recipe",
            "Users can view total cart price to purchase ingredients",
            "Users can alter recipe yield, which alters purchase amounts",
            "Users can view related recipes by similar ingredients",
            "Users can search by ingredient, method, or style",
            "Users can rate recipes",
            "Users can leave comments",
            "Users can follow links to buy directly online",
        ],
        github: "",
        live: "https://www.nobrainermeals.com"
    },
    {
        displayName: "Quiz App",
        name: "Quiz",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075793/quiz_z8dyyg.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075793/quiz_z8dyyg.png",
        technologies: [
            "HTM",
            "CS",
            "Javascript",],
        features: [
            "View a series of Monty Python themed multiple choice questions",
            "Quiz is timed allowing a total of 10 seconds per question",
            "User is presented with a timer indicator that starts as green and fades to red",
            "Timer indicator flashes green on correct response and red on incorrect",
            "Users' time has 10 seconds deducted on incorrect responses",
            "Quiz ends at 0 seconds or all questions answered",
            "Users' top 10 high scores are saved in local storage.",
        ],
        github: "github.com/Drantho/QuizApp",
        live: "drantho.github.io/QuizApp/"
    },
    {
        displayName: "Peninsula RV",
        name: "PeninsulaRV",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075793/peninsularv_tyij9b.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075793/peninsularv_tyij9b.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "Bootstrap",
            ".NET",
            "C#",
            "MSSQL",
        ],
        features: [
            "Visitors can view basic business information",
            "Visitors can view inventory and photos",
            "Users can add customer info",
            "Users can add vehicle info",
            "Users can upload photos",
            "Users can add repair orders",
            "Users can print receipts for work",
            "Users can add consignment info and print contract",
            "Users can add vehicle sale info and print contracts and forms",
            "Users can track post-sale process through payoff, taxes, licensing, and viewing profit",
            "Users can view monthly sales and tax reports",
            "Users can generate salesman commission documents",
            "Users can track customer leads and search inventory with ranked results            ",
        ],
        github: "",
        live: ""
    },
    {
        displayName: "Monthly Land Surface Temperature Graph",
        name: "MonthlyLandSurfaceTempGraph",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075795/tempgraph_ckuoar.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075795/tempgraph_ckuoar.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "D3",
        ],
        features: [
            "Users can see chart of global land surface average temp by month",
            "Users can see specific month data"
        ],
        github: "",
        live: "https://cdpn.io/drantho/debug/bRzyVa/xnMabmvYwEjr",
        codepen: "https://codepen.io/drantho/pen/bRzyVa"
    },
    {
        displayName: "So Thirsty",
        name: "SoThirsty",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075801/sothirsty_e6sue6.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075801/sothirsty_e6sue6.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "CSS",
            "Node",
            "Express",
            "MySQL",
            "Sequelize",
            "Handlebars",
            "Foundation CSS",
            "Nodemailer",
            "Bcrypt",
            "Toastify JS",
            "Cloudinary"
        ],
        features: [
            "User Authentication",
            "Plant search API",
            "Add plants to List",
            "Full CRUD functionality for plants in list",
            "Get reminders when watering is due",
            "Upload and delete photos",
            "Set privacy setting and share/view community photos",
            "Invite users to have limited access to view and set plants as woatered",
            "Send email invitation with private link with Authentication url",
            "Revoke limited user access"
        ],
        github: "https://github.com/Calmanning/so_thirsty",
        live: "https://sothirstyproject.herokuapp.com/"
    },
    {
        displayName: "Therapy Soon",
        name: "TherapySoon",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075802/therapysoon_zzfrgl.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075802/therapysoon_zzfrgl.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "Material Design",
            ".NET",
            "C#",
            "MSSQL            ",
        ],
        features: [
            "Admin users can create custom professional therapist categories",
            "Admin users can review and approve professional therapist applicants",
            "Users can apply to put detailed listing on site",
            "Users can pay for service with monthly online billing",
            "Users can upload photos",
            "Users can set availability",
            "Visitors can search for therapists by custom criteria",
            "Visitors can see lists of users ranked by relevant searches",
            "Visitors can search by distance from desired location            ",
        ],
        github: "",
        live: "https://therapysoon.com/"
    },
    {
        displayName: "Weather App",
        name: "WeatherApp",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075793/weather_p67baq.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075793/weather_p67baq.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
        ],
        features: [
            "User presented with current location, based on IP, on page load",
            "Search any city on earth(some small cities not included)",
            "Search by city adding state and/or country code",
            "List of possible results if search by city alone yields more than one response",
            "Searches are saved in a clickable list",
            "User can see current weather details.",
            "User can see 5 day forecast details.",
            "Background changes based on weather description.",
            "UV warnings color-coded by severity.",
        ],
        github: "",
        live: ""
    },
    {
        displayName: "Game of Life",
        name: "GameOfLife",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075786/gameoflife_eaarj6.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075786/gameoflife_eaarj6.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
        ],
        features: [
            "Users can play the Game of Life!"
        ],
        github: "",
        live: "https://cdpn.io/drantho/debug/YVMzjG/LQkExgVEXvLA",
        codepen: "https://codepen.io/drantho/pen/YVMzjG"
    },
    {
        displayName: "What to Do",
        name: "WhatToDo",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075804/whattodo_ohsdh1.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075804/whattodo_ohsdh1.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "Materialize CSS"
        ],
        features: [
            "View calendar by day, week, or month.",
            "Add custom categorized events.",
            "View and add suggested activities by type.",
            "View and cycle through inspirational quotes."
        ],
        github: "github.com/Z1springer/what_to_do",
        live: "z1springer.github.io/what_to_do/"
    },
    {
        displayName: "State Contiguity Chart",
        name: "StateContiguity",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075803/statecontiguity_jldxtr.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075803/statecontiguity_jldxtr.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "D3",
        ],
        features: [
            "Users can view world state contiguity map",
            "Users can click and drag stretchy border connections and rearrange chart",
        ],
        github: "",
        live: "https://cdpn.io/drantho/debug/WOBrKw/dGMXWjmEgqqk",
        codepen: "https://codepen.io/drantho/details/WOBrKw"
    },
    {
        displayName: "Machine Maintenance",
        name: "Maintenance",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075786/maintenance_p6abtp.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075786/maintenance_p6abtp.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "Bootstrap",
            "JQuery",
            ".NET",
            "C#",
            "MSSQL",
        ],
        features: [
            "Private protected app",
            "Users can create departments",
            "Users can create machine and add to department",
            "Users can add repair notes and times to machines",
            "Users can iupload photos of machines and repairs",
            "Users can create custom recurring checklist items",
            "Users can complete checklist items and leave notes",
            "Users can add suppliers' information",
            "Users can add parts information and link to machines and suppliers",
            "Users can add shelf labels and add parts to shelves",
            "Users can browse repairs by date or machine",
            "Users can view printable repair time reports by month, department, and machine            ",
        ],
        github: "",
        live: ""
    },
    {
        displayName: "Chart the Stock Market",
        name: "ChartTheStockMarket",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075800/stockmarket_dupkpx.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075800/stockmarket_dupkpx.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "Mongo",
            "Express",
            "Node",
            "Handlebars",
            "Material Design            ",
        ],
        features: [
            "Users can create custom polls",
            "Users can add responses to polls",
            "Users can respond to polls",
            "Users can tweet polls",
            "Users can view chart of poll responses            ",
        ],
        github: "https://github.com/Drantho/votingapp",
        live: ""
    },
    {
        displayName: "Random Password Generator",
        name: "RandomPasswordGenerator",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075799/passwordgen_wupskx.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075799/passwordgen_wupskx.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
        ],
        features: [
            "User can select what type of characters to include in password",
            "User can select length of password",
            "User can view settings",
            "User is provided with select password link",
            "User can manually customize password",
        ],
        github: "github.com/Drantho/PasswordGenerator",
        live: "drantho.github.io/PasswordGenerator/"
    },
    {
        displayName: "Minterest",
        name: "Minterest",
        image: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_475/v1614075804/minterest_xzj1sh.png",
        largeImage: "https://res.cloudinary.com/drantho/image/upload/c_fill,w_1080/v1614075804/minterest_xzj1sh.png",
        technologies: [
            "HTML",
            "CSS",
            "Javascript",
            "JQuery",
            "Mongo",
            "Express",
            "React",
            "Node            ",
        ],
        features: [
            "Pinterest clone"
        ],
        github: "",
        live: ""
    }
]

module.exports = data;